# Generated by Django 6.1.1 on 2026-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200, verbose_name='Titulli i Projektit')),
                ('slug', models.SlugField(unique=True)),
                ('klienti', models.CharField(blank=True, max_length=150, verbose_name='Klienti')),
                ('vendi', models.CharField(max_length=100, verbose_name='Vendndodhja (Qyteti/Zona)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Gjerësia Gjeografike (Latitude)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Gjatësia Gjeografike (Longitude)')),
                ('pershkrimi', models.TextField(verbose_name='Përshkrimi i Projektit')),
                ('imazhi_kryesor', models.ImageField(upload_to='projektet/', verbose_name='Imazhi Kryesor')),
                ('data_perfundimit', models.DateField(verbose_name='Data e Përfundimit')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektet',
            },
        ),
    ]
