# Generated by Django 6.1.1 on 2026-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sherbimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=150, verbose_name='Titulli i Shërbimit')),
                ('slug', models.SlugField(unique=True)),
                ('ikona_bootstrap', models.CharField(default='bi-layers', help_text='Emri i ikonës nga Bootstrap Icons (p.sh. bi-geo-alt, bi-layers)', max_length=50)),
                ('pershkrimi_i_shkurtër', models.TextField(max_length=300, verbose_name='Përshkrimi i Shkurtër')),
                ('permbajtja_detajuar', models.TextField(verbose_name='Përmbajtja e Detajuar')),
                ('imazhi', models.ImageField(blank=True, null=True, upload_to='sherbimet/')),
                ('renditja', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shërbim',
                'verbose_name_plural': 'Shërbimet',
                'ordering': ['renditja'],
            },
        ),
    ]
